
#
# Here you can specify custom damage types.
# There are several builtin damage types that correspond to vanilla damage sources. You can add your own types, for
# use in protection and damage bonuses, and by the Damage action damage_type parameter.
#
# For each damage type you can specify a max reduction % allowed. This is by how much damage is reduced for a player
# that has maxed out protection for that source.
#
# You can also specify max_strength- this is the damage multiplier that an attacker will receive if they have a "strength"
# of 1.
#
# And max_weakness is the damage multiplier that a defender will receive if they have a "weakness" of 1.
#
# For instance, if you have fire damage set to max_reduction of 0.5, a player with a protection.fire of 1.0 (100%, maxed out)
# will take 50% damage from all fire sources. A player with protection.fire of 0.5 will take 25% damage.
#
# Protection will never be allowed to go above 100% of the values specified here. Even if using stacking items, if a player
# has armor with protection.fire of 0.7 and holding a wand with protection.fire of 0.5, they will stack but cap at 1.0
#
# However, "overall" protection does stack with the other amounts, so take care with that. If the protection values
# add up to over 1.0 the player is completely immune to that type of damage.
#
# The "overall" type is special, it applies to the "overall" protection which will be used for any type of damage.
#
damage_types:
  overall:
    max_reduction: 0.2
    max_strength: 2
    max_weakness: 2
  explosion:
    max_reduction: 0.2
    max_strength: 2
    max_weakness: 2
  fall:
    max_reduction: 1.0
    max_strength: 2
    max_weakness: 2
  fire:
    max_reduction: 0.5
    max_strength: 2
    max_weakness: 2
  physical:
    max_reduction: 0.6
    max_strength: 2
    max_weakness: 2
  projectile:
    max_reduction: 0.2
    max_strength: 2
    max_weakness: 2
  magic:
    max_reduction: 0.5
    max_strength: 2
    max_weakness: 2
