## Work-in-Progress or not-fully-functional options

# Whether or not to show (or broadcast) cast messages as holotext
# (This feature was WIP and never really worked)
show_cast_holotext: false
cast_holotext_range: 0

# Whether or not to show (or broadcast) spell activate holotext
# (This feature was WIP and never really worked)
show_activate_holotext: false
activate_holotext_range: 0

## Deprecated configuration options

# These hacks should not be required in 1.8 and up
# This enables the item drag event interceptor
enable_custom_item_hacks: false

# Wands will switch to chest mode when the player is in creative mode
wand_creative_chest_switch: false

# Used as a work-around for enchanting since the main item may not be enchantable (client-side).
# wand_item_enchantable: wood_sword
wand_item_enchantable:

# If set to non-zero, represents a time (in milliseconds) after which all spells will be reversed.
auto_undo: 0

# Throttle TNT explosions
# This is built-in to Spigot, so generally not needed here.
max_tnt_per_chunk: 0

# The default enchanting path.
# Paths should be defined per-wand, though this could be used to "update" old wands with no
# path to some specific path.
default_wand_path:

# Set this to false to not write default configs out to the defaults folder.
save_default_configs: true

# Whether wands can be upgraded on an enchanting table
# This does not affect spellshop-based progression, but rather wands being enchanted via vanilla
# mechanics, something that no longer works.
enable_enchanting: false

# Whether wands can be combined on an anvil
enable_combining: false

# Whether renaming on an anvil will also clear the description
# In the future, it may be possible to change the description on
# an anvil.
anvil_rename_clears_description: false

# Whether or not using a wand on an anvil will organize its inventory
enable_organizing: false

# Players keep their wands when they die
# This is better confrolled via the "keep" property on wand configs.
keep_wands_on_death: false
