#
# These are examples that can be fetched via the `/mconfig fetch` command
#
external_examples:
  potterplus: "https://github.com/PotterPlus/PotterPlus/archive/master.zip"
  superheroes: "https://github.com/elBukkit/Magic-Superheroes/archive/main.zip"
  extramobs: "https://github.com/PhvntxmX/Magic-Bosses/archive/main.zip"
  mars: "https://github.com/elBukkit/Magic-Mars/archive/main.zip"
