# These define mappings of materials for backwards compatibility
ground_sign_block: sign_post,sign
wall_sign_block: wall_sign
firework: firework,firework_rocket
wall_torch: wall_torch,torch
redstone_torch_on: redstone_torch_on,redstone_torch:1
redstone_torch_off: redstone_torch_on,redstone_torch:0
redstone_wall_torch_on: redstone_torch_on,redstone_wall_torch:4
redstone_wall_torch_off: redstone_torch_on,redstone_torch:0
mob_spawner: spawner,mob_spawner
filled_map: filled_map,map