# This is a modifier on the default survival configs
require: survival

# Allow overriding so we can mix hires+robes in any order
example_override: true

# This references a builtin alternate_resource_pack
resource_pack: robes
add_resource_pack: robes

# Override the hires RP so it loads the robes version
alternate_resource_packs:
  hires:
    url: "http://rp.elmakers.com/Magic-hires-robes-RP-1.19.zip"
