# This is a modifier on the default survival configs
inherit: survival

resource_pack: "http://rp.elmakers.com/Magic-all-RP-1.17.zip"
add_resource_pack: "http://rp.elmakers.com/Magic-all-RP-1.17.zip"

# Alternate resource packs can be accessed with /getrp <pack>
alternate_resource_packs:
  robes:
    url: "http://rp.elmakers.com/Magic-all-RP-1.17.zip"
