# This IS a dev server, after all!
log_verbosity: 10
debug_effects: true

# Creative mode is super annoying sometimes
prevent_creative_breaking: 0

# Don't reduce melee damage anymore, it makes testing item attributes and damage too difficult!
# melee_damage_reduction: 0.5

# Turn on auto-rollback for creeper explosions and TNT
auto_rollback_duration: 10000
auto_rollback_speed: 0.5
auto_rollback_explosions:
- creeper
- primed_tnt

# We are mixing in all of the configs here to show them off.
add_examples:
- stars
- potter
- bending
- war
- rpg
- arenas

# Testing custom costs
custom_costs:
 - tc
 - ac

# Just leaving this here for now, to re-enable wand enchanting:
# enable_enchanting: true
# sp_enabled: false
# enchant_click: ""
# wand_item_enchantable: wood_sword

# resource_pack_prompt: true

# resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-all-RP-TESTING.zip"
# add_resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-all-RP-TESTING.zip"
