# This is a modifier on the default survival configs
inherit: survival

# Disable the resource pack.
resource_pack: ""
add_resource_pack: ""

# Turn back on skull-based icons
# They will look like cubes without any RP though.
url_icons_enabled: true
