# This is a modifier on the default survival configs
inherit: survival

# Show enchantments on wands
# Note that if using the "glow" property on wands a "Luck of the Sea" enchantment will show if no other
# enchantments are set.
wand_hide_flags: 62

# Don't send cast messages in the action bar
cast_message_prefix: "&5&o"

# Don't let players put wands in chests or drag them out of their inventories
wand_undroppable: true
