resource_pack: "http://rp.elmakers.com/Magic-RP-1.18.zip"
add_resource_pack: "http://rp.elmakers.com/Magic-all-RP-1.18.zip"

alternate_resource_packs:
  borders:
    url: "http://rp.elmakers.com/Magic-potter-RP-1.18.zip"
  painterly:
    url: "http://rp.elmakers.com/Magic-painterly-RP-1.18.zip"
  lowres:
    url: "http://rp.elmakers.com/Magic-lowres-RP-1.18.zip"
  hires:
    url: "http://rp.elmakers.com/Magic-hires-RP-1.18.zip"
  skulls:
    url: "http://rp.elmakers.com/Magic-skulls-RP-1.18.zip"
    url_icons_enabled: true
  survival:
    url: "http://rp.elmakers.com/Magic-RP-1.18.zip"
  all:
    url: "http://rp.elmakers.com/Magic-all-RP-1.18.zip"
