#
# Set up for an RPG-style server, with different classes for players to choose from.
#

# No SP system here
sp_enabled: false

# This is a modifier on the default survival configs
inherit: survival

# Turn off the survival spells, but allow them to be inherited from
disable_inherited:
 - spells

skip_inherited:
 - wands
 - paths
 - crafting
 - classes
 -
# Default class
default_mage_class: peasant

# Turn off the enchant table
enchant_click: ""
enchant_sneak_click: ""

custom_currency:
 ap:
  max: 100
  default: 20
  icon: skull:http://textures.minecraft.net/texture/b11206551e723c356c23b32383abd19e6d7e9e5988f191e7866ae89ed6cb24
