#
# Set up for a Harry Potter server.
#
# Crafting is not allowed, it is assumed each player has one wand
# they will keep throughout their play experience.
#

# Give the player a Ticket from Ollivander to start their journey
# This can be exchanged for a Wand Box from an NPC by doing the following:
# /npc create Ollivander
# /trait magic
# /mtrait spell ollivander
welcome_wand: ticket

default_wand: potterwand

# Start players off with some Spell Points
sp_default: 100

# This is a modifier on the default survival configs
inherit: survival

# Turn off the survival spells, but allow them to be inherited from
disable_inherited:
 - spells

skip_inherited:
 - wands
 - paths
 - crafting
 - classes
 - mobs

# Don't allow crafting
enable_crafting: false

# Custom physical economy
currency:
  emerald:
    worth: 1
    name: Galleon
    name_plural: Galleons
    
# Use the potter RP
resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-potter-RP-7.zip"

# Default class
default_mage_class: wizard

# Set up some custom currency
custom_currency:
 tc:
  max: 9999
  default: 0
 ac:
  max: 9999
  default: 0