#
# Set up for a Harry Potter server.
#
# Crafting is not allowed, it is assumed each player has one wand
# they will keep throughout their play experience.
#

# Give the player a Ticket from Ollivander to start their journey
# This can be exchanged for a Wand Box from an NPC by doing the following:
# /npc create Ollivander
# /trait magic
# /mtrait spell ollivander
welcome_wand: ticket

default_wand: potterwand

# Start players off with some Spell Points
sp_default: 100

# This is a complete wand/spell overhaul
load_default_spells: true
disable_default_spells: true
load_default_wands: false
load_default_classes: true
load_default_paths: false
load_default_crafting: false

# Don't allow crafting
enable_crafting: false

# Don't allow combining
enable_combining: false

# Disable the enchantment table showing the spell shop or upgrades
enchant_block: ""

# Wands don't glow because they don't in the movies
wand_glow: false

# Custom physical economy
currency:
  emerald:
    worth: 1
    name: Galleon
    name_plural: Galleons
    
# Use the potter RP
resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-potter-RP-6-4.zip"